[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "build-feedstock"
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]
version = "0.1.0"

[dependencies]
foobar = { path = "./recipe" }
foobar-desktop = { path = "./recipe" }
