[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
description = "Add a short description here"
name = "build-recipe"
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]
version = "0.1.0"

[tasks]

[dependencies]
bzip2 = { path = "./recipes/bzip2" }
python = "3.12.*"
